# DATA CLEANING-1

In [4]:
import numpy as np
import pandas as pd


## Missing Data
    What does "missing data" mean? What is a missing value? It depends on the origin of the data and the context it was generated. For example, for a survey, a Salary field with an empty value, or a number 0, or an invalid value (a string for example) can be considered "missing data". These concepts are related to the values that Python will consider "Falsy"

In [5]:
falsy_values=(0, False, None, '', [], {})



In [6]:
any(falsy_values)

False

In [7]:
np.nan 

nan

Be careful with np.nan-> it is virus like, anything that it touches becomes a NaN value.

In [8]:
3+np.nan

nan

In [9]:
a = np.array([1, 2, 3, np.nan, np.nan, 4])


In [10]:
print(a.mean(),'\n',a.sum())

nan 
 nan


In [12]:
3 + None 

TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'

this gave an error because their types are different!!

In [14]:
a = np.array([1, 2, 3, np.nan, np.nan, 4], dtype='float')
a

array([ 1.,  2.,  3., nan, nan,  4.])

In [15]:
print(a.mean(),'\n', a.sum())

nan 
 nan


numpy also has an infinity function which serves as a virus (just like np.nan)

In [17]:
np.inf  #INFINITE!

inf

## Checking for inf or nan
    np.isnan() and np.isinf() and the joint operation is performed using np.isfinite()

In [20]:
np.isnan(np.array([1, 2, 3, np.nan, np.nan, 4])
)

array([False, False, False,  True,  True, False])

In [21]:
np.isinf(np.array([1, 2, 3, np.nan, np.nan, 4]))


array([False, False, False, False, False, False])

In [23]:
np.isfinite(np.array([1, 2, 3, np.nan, np.nan, 4]))

array([ True,  True,  True, False, False,  True])

## Filtering them out:
    a[~np.isnan()]

In [25]:
a[~np.isnan(a)]


array([1., 2., 3., 4.])