# Arrays
Here we show how to use basic arrays, how to concatenate, add, change type, call type,etc

In [1]:
import numpy as np
a=np.array([1, 2, 3, 4])
b=np.array([0, 0.5, 1, 1.5, 2])
print(a[0]+b[1])
print(a[[0,3]])
print(a.dtype)
c=np.array([1,4,5], dtype=np.float64)
print(c)

1.5
[1 4]
int32
[1. 4. 5.]


### Array Dimensions and shapes
Basically stuff like matrices and how to work with them


In [2]:
A=np.array([
    [1, 2, 3],
    [4, 5, 6]
])
A.shape #basic shape of matrix



(2, 3)

In [3]:
A.ndim #number of dimensions


2

In [4]:
A.size #number of elements

6

In [5]:
B=np.array([
    [
        [1, 2, 13],
        [21, 2, 3]
    ],
    [
        [32, 23, 12],
        [11, 1, 2]
    ]
])
print(B)

[[[ 1  2 13]
  [21  2  3]]

 [[32 23 12]
  [11  1  2]]]


In [6]:
B.shape

(2, 2, 3)

In [7]:
B.ndim

3

In [8]:
B.size

12

### Indexing and Slicing of Matrices
Now all we need to do is account for the varying size and dimensions

In [9]:
A= np.array([
    # 0 1 2
    [1, 2, 3], #0
    [4, 5, 6], #1
    [7, 8, 9]  #2
])

In [10]:
A[1]

array([4, 5, 6])

In [11]:
A[0][1]

2

In [12]:
A[0,1] #this is the same as before, but it will allow some sort of splicing advantages later on!

2

In [13]:
A[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
A[:, :2] #I want every row, but only the 0th and 1st numbers

array([[1, 2],
       [4, 5],
       [7, 8]])

In [15]:
A[1]=np.array([10,10,10]) #modifying array
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [ 7,  8,  9]])

### Summary and Statistics
Some Mathematical tools

In [16]:
x=np.array([1,2,3,4,5,6])
x


array([1, 2, 3, 4, 5, 6])

In [17]:
x.sum()

21

In [18]:
x.mean()

3.5

In [19]:
x.std()

1.707825127659933

In [20]:
x.var()

2.9166666666666665

In [21]:
A.sum() #working with a 2D array

60

In [22]:
A.mean()

6.666666666666667

Now, we can also do a sum along the axis. 
Like if we have an array like *A* then we can say that it is a 2D array, wherein **axis=0** means columns and **axis=1** means rows

In [23]:
A.sum(axis=0) #sum of the 1st,2nd and 3rd columns

array([18, 20, 22])

# NUMPY Operations

### BROADCASTING AND VECTORIZED OPERATIONS

In [38]:
y=np.arange(4)
y

array([0, 1, 2, 3])

See whatever we do to *y* gets applied to all the elements within it. Also, an important point to remember is that we are creating a new array and not modifying the already existing one!

In [39]:
y+10


array([10, 11, 12, 13])

In [40]:
y*10

array([ 0, 10, 20, 30])

In [42]:
y #see how it didn't change

array([0, 1, 2, 3])

In [43]:
y+=100 #but now we're modifying the actual thing
y

array([100, 101, 102, 103])

### Basic Addition, Subtraction, multiplication,etc can also be done

In [44]:
z=np.array([10,12,13,14])

In [45]:
z+y

array([110, 113, 115, 117])

In [46]:
z-y

array([-90, -89, -89, -89])

In [47]:
z*y

array([1000, 1212, 1326, 1442])

In [48]:
z/y

array([0.1       , 0.11881188, 0.12745098, 0.13592233])

# NUMPY Boolean Operations
Also called *Masks*

In [50]:
p=np.arange(4)
p

array([0, 1, 2, 3])

In [51]:
p[[True, False, True, True]] #basically another way of selecting elements

array([0, 2, 3])

In [58]:
p>=2 #this is something very powerful!

array([False, False,  True,  True])

Filtering or quering

In [57]:
p[p>=2] 

array([2, 3])

In [59]:
p[p> p.mean()]

array([2, 3])

In [60]:
p[~(p>p.mean())] #less than the mean

array([0, 1])

In [61]:
p[(p==1)| (p==0)] #Boolen OR operator

array([0, 1])

In [62]:
p[(p<=2) & (p%2==0)] #Boolean AND

array([0, 2])

In [63]:
Q=np.random.randint(100, size=(3,3)) #with a 2D array
Q

array([[36, 34, 85],
       [ 7, 60, 13],
       [60, 45, 93]])

In [64]:
Q[Q>30]

array([36, 34, 85, 60, 60, 45, 93])

# NUMPY ALGEBRA AND SIZE

In [66]:
R=np.array([
    [1, 2, 3],
    [4,5,6],
    [7,8,9]
])
S=np.array([
    [6,5],
    [4,3],
    [2,1]
])

In [67]:
R.dot(S)

array([[20, 14],
       [56, 41],
       [92, 68]])

In [69]:
R @ S #another way to show dot product

array([[20, 14],
       [56, 41],
       [92, 68]])

In [70]:
S.T #transposing

array([[6, 4, 2],
       [5, 3, 1]])

In [71]:
S.T @ R #multiplicating after transposing

array([[36, 48, 60],
       [24, 33, 42]])

## Size of Objects in Memory

In [72]:
import sys

In [73]:
sys.getsizeof(1) #an integer always has a size > 24 bytes 

28

In [74]:
sys.getsizeof(10**100) #longs are even longer!!

72

system sizes are much longer, but numpy ones are much much smaller

In [75]:
np.dtype(int).itemsize 

4

In [76]:
np.dtype(np.int8).itemsize

1

In [77]:
np.dtype(float).itemsize

8

Lists are larger! but even here numpy is smaller

In [79]:
sys.getsizeof(1)


28

In [80]:
np.array([1]).nbytes

4

#### Performance is also important
Here also we can see the superiority that numpy offers over raw python

In [81]:
l=list(range(1000))

In [83]:
u=np.array(1000)

In [84]:
%time sum([i**2 for i in l])

Wall time: 997 µs


332833500

In [85]:
%time np.sum(u**2)

Wall time: 0 ns


1000000

# SOME useful NUMPY Functions

## Random

In [86]:
np.random.random(size=2)

array([0.97212076, 0.97044102])

In [87]:
np.random.normal(size=3)

array([ 0.5012844 ,  0.20960137, -0.77556289])

## Arange

In [88]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [91]:
np.arange(5,10,0.1)

array([5. , 5.1, 5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1, 6.2,
       6.3, 6.4, 6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4, 7.5,
       7.6, 7.7, 7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7, 8.8,
       8.9, 9. , 9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9])

## Reshape

In [92]:
np.arange(10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [95]:
np.arange(10).reshape(5,2) # reshaping is only allowed in integral factors of the size given (here it is 10)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

## Linspace

In [96]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [97]:
np.linspace(0,1,20,False)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

## Zeros, Ones, Empty

In [99]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [100]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [101]:
np.ones((2,100))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.]])

In [102]:
np.empty((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

## Identity and Eye

In [103]:
np.identity(3) #identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [104]:
np.eye(8,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [106]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [109]:
np.eye(8,4,k=-3)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [110]:
np.eye(8,4,k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])